name: Node API CI

on:
  push:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Updated version
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Updated version
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: ./ebook-api

      - name: Run Check
        run: node -e "console.log('API Build Success')"
        working-directory: ./ebook-api